#:schema node_modules/wrangler/config-schema.json
name = "lucas-sublink"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "3943210c4464480eafa46afaec13d1ad" }
]

[assets]
directory = "./public"
